-- Referral-based product sales platform schema
CREATE DATABASE IF NOT EXISTS referral_platform CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
USE referral_platform;

-- ---------------------------------------------------------------
CREATE TABLE products (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(150) NOT NULL,
    description TEXT DEFAULT NULL,
    srp DECIMAL(10,2) NOT NULL DEFAULT 210.00,
    image VARCHAR(255) DEFAULT NULL,
    status ENUM('active','inactive') NOT NULL DEFAULT 'active',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB;

-- Extra marketing/highlight images shown on a product's profile page.
-- Unlike `products.image` (the one main catalog photo), a product can have
-- any number of these (or none).
CREATE TABLE product_images (
    id INT AUTO_INCREMENT PRIMARY KEY,
    product_id INT NOT NULL,
    image VARCHAR(255) NOT NULL,
    sort_order INT NOT NULL DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE CASCADE
) ENGINE=InnoDB;

-- JMC Foodies Wellness member accounts. Wellness and Basics are fully
-- separate account systems (each with its own login/registration/session) —
-- see basics_users below for the Basics equivalent. There is no shared
-- login between the two modules.
CREATE TABLE users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    referral_code VARCHAR(20) NOT NULL UNIQUE,
    referred_by INT DEFAULT NULL,
    full_name VARCHAR(150) NOT NULL,
    address VARCHAR(255) NOT NULL,
    birthdate DATE NOT NULL,
    contact_number VARCHAR(30) NOT NULL,
    email VARCHAR(190) NULL UNIQUE,
    username VARCHAR(100) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    must_change_password TINYINT(1) NOT NULL DEFAULT 1,
    status ENUM('pending','active','suspended') NOT NULL DEFAULT 'pending',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (referred_by) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB;

-- JMC Foodies Basics member accounts — a separate account system from
-- Wellness's `users` table (no referral program in Basics, so no
-- referral_code/referred_by columns here).
CREATE TABLE basics_users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    full_name VARCHAR(150) NOT NULL,
    address VARCHAR(255) NOT NULL,
    birthdate DATE NOT NULL,
    contact_number VARCHAR(30) NOT NULL,
    email VARCHAR(190) NULL UNIQUE,
    username VARCHAR(100) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    must_change_password TINYINT(1) NOT NULL DEFAULT 1,
    status ENUM('pending','active','suspended') NOT NULL DEFAULT 'pending',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB;

-- Wellness admin accounts (admin/login.php). Separate from basics_admins
-- below — a Wellness admin cannot log into Basics admin, and vice versa.
CREATE TABLE admins (
    id INT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(100) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    name VARCHAR(150) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB;

-- Basics admin accounts (basics/admin/login.php).
CREATE TABLE basics_admins (
    id INT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(100) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    name VARCHAR(150) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB;

-- Admin action audit trail — fed by BOTH the Wellness admin panel (admins)
-- and the Basics admin panel (basics_admins), disambiguated by admin_type.
-- No FK on admin_id since it can point into either table; admin_name is a
-- snapshot, so entries stay readable regardless.
CREATE TABLE activity_log (
    id INT AUTO_INCREMENT PRIMARY KEY,
    admin_id INT DEFAULT NULL,
    admin_type ENUM('wellness','basics') DEFAULT NULL,
    admin_name VARCHAR(150) DEFAULT NULL,
    action VARCHAR(100) NOT NULL,
    description VARCHAR(255) NOT NULL,
    ip_address VARCHAR(45) DEFAULT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB;

CREATE TABLE orders (
    id INT AUTO_INCREMENT PRIMARY KEY,
    user_id INT NOT NULL,
    product_id INT NOT NULL,
    quantity INT NOT NULL DEFAULT 1,
    unit_price DECIMAL(10,2) NOT NULL,
    total_amount DECIMAL(10,2) NOT NULL,
    payment_method ENUM('wallet','bank_transfer','cod') NOT NULL,
    payment_reference VARCHAR(100) DEFAULT NULL,
    status ENUM('pending','processing','completed','cancelled') NOT NULL DEFAULT 'pending',
    confirmed_at TIMESTAMP NULL DEFAULT NULL,
    confirmed_by INT DEFAULT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE RESTRICT,
    FOREIGN KEY (confirmed_by) REFERENCES admins(id) ON DELETE SET NULL
) ENGINE=InnoDB;

CREATE TABLE cashouts (
    id INT AUTO_INCREMENT PRIMARY KEY,
    user_id INT NOT NULL,
    bank_name VARCHAR(100) NOT NULL,
    amount DECIMAL(10,2) NOT NULL,
    fee_amount DECIMAL(10,2) NOT NULL DEFAULT 0,
    net_amount DECIMAL(10,2) NOT NULL DEFAULT 0,
    account_number VARCHAR(50) NOT NULL,
    account_name VARCHAR(150) NOT NULL,
    status ENUM('pending','approved','rejected') NOT NULL DEFAULT 'pending',
    admin_notes VARCHAR(255) DEFAULT NULL,
    processed_by INT DEFAULT NULL,
    processed_at TIMESTAMP NULL DEFAULT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    FOREIGN KEY (processed_by) REFERENCES admins(id) ON DELETE SET NULL
) ENGINE=InnoDB;

-- Editable business settings (rebate/override rates, min cashout, contact
-- email) — managed from admin/settings.php instead of hardcoded constants.
CREATE TABLE settings (
    setting_key VARCHAR(100) PRIMARY KEY,
    setting_value VARCHAR(255) NOT NULL
) ENGINE=InnoDB;

CREATE TABLE wallet_transactions (
    id INT AUTO_INCREMENT PRIMARY KEY,
    user_id INT NOT NULL,
    type ENUM('personal_rebate','referral_override','purchase_wallet_debit','purchase_refund','cashout','cashout_reversal') NOT NULL,
    amount DECIMAL(10,2) NOT NULL,
    reference_order_id INT DEFAULT NULL,
    reference_cashout_id INT DEFAULT NULL,
    description VARCHAR(255) DEFAULT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    FOREIGN KEY (reference_order_id) REFERENCES orders(id) ON DELETE SET NULL,
    FOREIGN KEY (reference_cashout_id) REFERENCES cashouts(id) ON DELETE SET NULL
) ENGINE=InnoDB;

-- ---------------------------------------------------------------
-- Seed data
INSERT INTO products (name, description, srp, image, status) VALUES
('Activated Charcoal', 'Premium activated charcoal food supplement. 100 capsules, 560mg per capsule.', 699.00, 'activated-charcoal.png', 'active'),
('Premium Healthy Coffee Mix', 'Good coffee. Real nutrition. Better you. Natural antioxidant creamy white coffee with malunggay, spinach, inulin & collagen. Benefits in every cup. Net weight 110g.\n\nBenefits:\n- Boosts Immunity\n- Energy & Alertness\n- Improves Focus & Concentration\n- Supports Digestive Health\n- Natural Antioxidants\n- Collagen Peptides for Beauty\n- Nourishing Superfoods\n- Wellness for Your Daily Life', 230.00, 'healthy-coffee-mix.png', 'active'),
('Choco Wellness', 'Indulge in a creamy, delicious cup of wellness. Rich chocolate, collagen, prebiotic fiber & superfoods. Net weight 110g, makes approx. 7 cups. Proudly made in the Philippines.\n\nBenefits:\n- Supports Immunity: helps strengthen your body''s natural defenses\n- Rich in Antioxidants: helps fight free radicals and supports overall well-being\n- Natural Energy Boost: gentle, sustained energy to keep you active all day\n- Supports Digestive Health: contains prebiotic fiber (inulin) for a healthy gut and digestion\n- Healthy Skin, Hair & Nails: collagen helps promote healthy, radiant skin, strong hair and nails\n- Made with Superfoods: malunggay and spinach, nature''s powerful greens', 230.00, 'choco-wellness.png', 'active');

-- Extra highlight/marketing images (none for Activated Charcoal — no source images provided for it)
INSERT INTO product_images (product_id, image, sort_order) VALUES
(2, 'healthy-coffee-mix-catalog.jpg', 0),
(2, 'healthy-coffee-mix-catalog2.jpg', 1),
(3, 'choco-wellness-catalog.jpg', 0),
(3, 'choco-wellness-catalog2.jpg', 1);

INSERT INTO settings (setting_key, setting_value) VALUES
('personal_rebate_rate', '0.20'),
('referral_override_rate', '0.10'),
('min_cashout_amount', '1000.00'),
('cashout_processing_fee_rate', '0.10'),
('company_email', 'jmcdigital@gmail.com');

-- Default admin login: username "jmcadmin", password "AdminJMC#2026"
INSERT INTO admins (username, password_hash, name) VALUES
('jmcadmin', '$2y$10$b6NL0VAz2LLzMf/hyM/RMOuvjT5TJWIfdIl0H1cWLhFhIzpypi2NS', 'Administrator');

INSERT INTO basics_admins (username, password_hash, name) VALUES
('basicsadmin', '$2y$10$0MY.czmOiS6deRkpxg.o.OpfvbXzupy2C8ZzUIaueqoXUBQ68cRay', 'Basics Administrator');

-- Seed root user (no referrer) so real registrations have a code to chain from.
-- Login: username "jmcuser", password "Founder2026"
INSERT INTO users (referral_code, referred_by, full_name, address, birthdate, contact_number, username, password_hash, must_change_password, status) VALUES
('JMC-FQL5U5CLG', NULL, 'Founding Member', 'Nueva Ecija, Philippines', '1990-01-01', '09170000000', 'jmcuser', '$2y$10$FEtuCV1fZGez6s8vLRSLwOD88mGaBJS0I31UdrUFXFP6dNLSt9QvO', 0, 'active');

-- ---------------------------------------------------------------
-- JMC Foodies Basics — grocery credit-line ordering system.
-- Shares the `users`/`admins` login tables above; a user "joins" Basics by
-- getting a row here (application_status starts 'pending', admin approves).
CREATE TABLE basics_members (
    id INT AUTO_INCREMENT PRIMARY KEY,
    user_id INT NOT NULL UNIQUE,
    employer_name VARCHAR(150) NOT NULL,
    employer_contact VARCHAR(100) DEFAULT NULL,
    position VARCHAR(100) DEFAULT NULL,
    application_status ENUM('pending','approved','denied') NOT NULL DEFAULT 'pending',
    membership_status ENUM('active','suspended','dormant','terminated') NOT NULL DEFAULT 'active',
    weekly_credit_limit DECIMAL(10,2) NOT NULL DEFAULT 0,
    emergency_credit_limit DECIMAL(10,2) NOT NULL DEFAULT 0,
    offense_count TINYINT UNSIGNED NOT NULL DEFAULT 0,
    consecutive_on_time_payments INT UNSIGNED NOT NULL DEFAULT 0,
    credit_limit_frozen TINYINT(1) NOT NULL DEFAULT 0,
    suspended_until DATE DEFAULT NULL,
    last_activity_at TIMESTAMP NULL DEFAULT NULL,
    reviewed_by INT DEFAULT NULL,
    reviewed_at TIMESTAMP NULL DEFAULT NULL,
    admin_notes VARCHAR(255) DEFAULT NULL,
    applied_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES basics_users(id) ON DELETE CASCADE,
    FOREIGN KEY (reviewed_by) REFERENCES basics_admins(id) ON DELETE SET NULL
) ENGINE=InnoDB;

-- KYC documents (2 valid IDs, Barangay Clearance, Application Form, COE).
-- Deliberately NOT served the way product images are — see uploads/basics_kyc/
-- .htaccess and basics/admin/kyc_view.php. These are government ID scans.
CREATE TABLE basics_kyc_documents (
    id INT AUTO_INCREMENT PRIMARY KEY,
    member_id INT NOT NULL,
    doc_type ENUM('valid_id_1','valid_id_2','barangay_clearance','membership_application_form','membership_application_form_back','certificate_of_employment') NOT NULL,
    file_path VARCHAR(255) NOT NULL,
    uploaded_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (member_id) REFERENCES basics_members(id) ON DELETE CASCADE
) ENGINE=InnoDB;

-- Sari-sari-store convenience goods catalog, 613 SKUs across 8 categories
-- (JMC_Foodies_Basics_*_Masterlist.pdf). srp is seeded at the low end of each
-- masterlist's price range; admin adjusts individual items via
-- basics/admin/product_edit.php.
CREATE TABLE basics_products (
    id INT AUTO_INCREMENT PRIMARY KEY,
    sku VARCHAR(20) NOT NULL UNIQUE,
    category ENUM('Rice','Food Essentials','Cooking Products','Beverages','Homecare','Personal Care','Palengke Items','Frozen Meat Products','Bread & Snacks') NOT NULL,
    name VARCHAR(150) NOT NULL,
    unit VARCHAR(50) NOT NULL,
    srp DECIMAL(10,2) NOT NULL DEFAULT 0,
    image VARCHAR(255) DEFAULT NULL,
    status ENUM('active','inactive') NOT NULL DEFAULT 'active',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB;

-- Weekly ordering windows (Mon-Thu order, Fri cutoff, Sat-Sun payment,
-- Sun/Mon delivery). `status` is a display cache only — window-gating logic
-- always recomputes from the date columns against today's date.
CREATE TABLE basics_cycles (
    id INT AUTO_INCREMENT PRIMARY KEY,
    label VARCHAR(50) NOT NULL,
    order_open_date DATE NOT NULL UNIQUE,
    order_cutoff_date DATE NOT NULL,
    payment_start_date DATE NOT NULL,
    payment_due_date DATE NOT NULL,
    delivery_date DATE NOT NULL,
    status ENUM('upcoming','ordering','cutoff','payment','delivered','closed') NOT NULL DEFAULT 'upcoming',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB;

-- One cart/order per member per cycle (multi-item, unlike Wellness's
-- single-product orders table).
CREATE TABLE basics_orders (
    id INT AUTO_INCREMENT PRIMARY KEY,
    member_id INT NOT NULL,
    cycle_id INT NOT NULL,
    total_amount DECIMAL(10,2) NOT NULL DEFAULT 0,
    -- status flips to 'paid' automatically (basics_record_payment(),
    -- basics/includes/functions.php) once payments cover total_amount.
    status ENUM('draft','pending','paid','delivered','cancelled') NOT NULL DEFAULT 'draft',
    placed_at TIMESTAMP NULL DEFAULT NULL,
    delivered_at TIMESTAMP NULL DEFAULT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (member_id) REFERENCES basics_members(id) ON DELETE CASCADE,
    FOREIGN KEY (cycle_id) REFERENCES basics_cycles(id) ON DELETE RESTRICT,
    UNIQUE KEY (member_id, cycle_id)
) ENGINE=InnoDB;

CREATE TABLE basics_order_items (
    id INT AUTO_INCREMENT PRIMARY KEY,
    order_id INT NOT NULL,
    product_id INT NOT NULL,
    quantity INT NOT NULL DEFAULT 1,
    unit_price DECIMAL(10,2) NOT NULL,
    line_total DECIMAL(10,2) NOT NULL,
    FOREIGN KEY (order_id) REFERENCES basics_orders(id) ON DELETE CASCADE,
    FOREIGN KEY (product_id) REFERENCES basics_products(id) ON DELETE RESTRICT
) ENGINE=InnoDB;

-- Settlement records. fee/net-style snapshot pattern (mirrors cashouts'
-- fee_amount/net_amount) so a later settings change never rewrites history.
CREATE TABLE basics_payments (
    id INT AUTO_INCREMENT PRIMARY KEY,
    order_id INT NOT NULL,
    member_id INT NOT NULL,
    amount_due DECIMAL(10,2) NOT NULL,
    penalty_rate DECIMAL(5,4) NOT NULL DEFAULT 0,
    penalty_amount DECIMAL(10,2) NOT NULL DEFAULT 0,
    amount_paid DECIMAL(10,2) NOT NULL DEFAULT 0,
    offense_number TINYINT UNSIGNED DEFAULT NULL,
    is_late TINYINT(1) NOT NULL DEFAULT 0,
    paid_at TIMESTAMP NULL DEFAULT NULL,
    recorded_by INT DEFAULT NULL,
    notes VARCHAR(255) DEFAULT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (order_id) REFERENCES basics_orders(id) ON DELETE CASCADE,
    FOREIGN KEY (member_id) REFERENCES basics_members(id) ON DELETE CASCADE,
    FOREIGN KEY (recorded_by) REFERENCES basics_admins(id) ON DELETE SET NULL
) ENGINE=InnoDB;

-- Emergency Cash Credit disbursement requests (up to emergency_credit_limit,
-- 0% interest per the program manual). A member requests an amount; admin
-- approves and records what was actually released (may differ from the
-- request if it would exceed their remaining limit) or denies it.
-- Outstanding balance is always derived (amount_released minus confirmed
-- repayments in basics_payment_submissions), not stored, so it can never
-- drift out of sync with the repayment ledger.
CREATE TABLE basics_emergency_credit_requests (
    id INT AUTO_INCREMENT PRIMARY KEY,
    member_id INT NOT NULL,
    amount_requested DECIMAL(10,2) NOT NULL,
    reason VARCHAR(255) DEFAULT NULL,
    status ENUM('pending','approved','denied') NOT NULL DEFAULT 'pending',
    amount_released DECIMAL(10,2) DEFAULT NULL,
    released_at TIMESTAMP NULL DEFAULT NULL,
    reviewed_by INT DEFAULT NULL,
    reviewed_at TIMESTAMP NULL DEFAULT NULL,
    admin_notes VARCHAR(255) DEFAULT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (member_id) REFERENCES basics_members(id) ON DELETE CASCADE,
    FOREIGN KEY (reviewed_by) REFERENCES basics_admins(id) ON DELETE SET NULL
) ENGINE=InnoDB;

-- Member-submitted proof of payment (GCash/Bank), pending admin review.
-- Confirming a 'grocery' submission calls basics_record_payment() against
-- order_id, which is what actually writes the basics_payments ledger row —
-- this table is just the member's claim + proof, not the ledger itself.
-- 'loan' submissions repay a specific basics_emergency_credit_requests row
-- (loan_request_id) — confirming one doesn't write elsewhere, since that
-- request's outstanding balance is derived by summing confirmed repayments.
-- 'other' submissions have nothing to link to; confirming is a manual
-- admin acknowledgement only.
CREATE TABLE basics_payment_submissions (
    id INT AUTO_INCREMENT PRIMARY KEY,
    member_id INT NOT NULL,
    payment_for ENUM('grocery','loan','other') NOT NULL,
    order_id INT DEFAULT NULL,
    loan_request_id INT DEFAULT NULL,
    payment_method ENUM('gcash','bank') NOT NULL,
    destination_account VARCHAR(150) NOT NULL,
    amount DECIMAL(10,2) NOT NULL,
    reference_number VARCHAR(100) NOT NULL,
    paid_at DATETIME NOT NULL,
    proof_image VARCHAR(255) DEFAULT NULL,
    status ENUM('pending','confirmed','rejected') NOT NULL DEFAULT 'pending',
    admin_notes VARCHAR(255) DEFAULT NULL,
    reviewed_by INT DEFAULT NULL,
    reviewed_at TIMESTAMP NULL DEFAULT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (member_id) REFERENCES basics_members(id) ON DELETE CASCADE,
    FOREIGN KEY (order_id) REFERENCES basics_orders(id) ON DELETE SET NULL,
    FOREIGN KEY (loan_request_id) REFERENCES basics_emergency_credit_requests(id) ON DELETE SET NULL,
    FOREIGN KEY (reviewed_by) REFERENCES basics_admins(id) ON DELETE SET NULL
) ENGINE=InnoDB;

-- Phase 2 benefit programs (program manual section 10): Electric Bill Cash
-- Subsidy, Hospital Financial Assistance, Burial Financial Assistance, Baon
-- Eskwela Subsidy — one shared request table for all four, like cashouts.
-- amount_due is what the member's bill/document shows; amount_paid is set
-- by the admin on approval (may be less, per program caps/fund availability).
-- relationship_to_deceased/deceased_address only apply to burial_assistance.
CREATE TABLE basics_benefit_requests (
    id INT AUTO_INCREMENT PRIMARY KEY,
    member_id INT NOT NULL,
    benefit_type ENUM('electric_subsidy','hospital_assistance','burial_assistance','baon_eskwela') NOT NULL,
    amount_due DECIMAL(10,2) NOT NULL,
    amount_paid DECIMAL(10,2) DEFAULT NULL,
    due_date DATE DEFAULT NULL,
    relationship_to_deceased VARCHAR(100) DEFAULT NULL,
    deceased_address VARCHAR(255) DEFAULT NULL,
    status ENUM('pending','approved','denied') NOT NULL DEFAULT 'pending',
    admin_notes VARCHAR(255) DEFAULT NULL,
    reviewed_by INT DEFAULT NULL,
    reviewed_at TIMESTAMP NULL DEFAULT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (member_id) REFERENCES basics_members(id) ON DELETE CASCADE,
    FOREIGN KEY (reviewed_by) REFERENCES basics_admins(id) ON DELETE SET NULL
) ENGINE=InnoDB;

-- Supporting documents per benefit request — which doc_types are required
-- depends on benefit_type (see basics_benefit_doc_requirements() in
-- basics/includes/functions.php). Not publicly servable — see
-- uploads/basics_benefit_docs/.htaccess and basics/admin/benefit_document_view.php.
CREATE TABLE basics_benefit_documents (
    id INT AUTO_INCREMENT PRIMARY KEY,
    request_id INT NOT NULL,
    doc_type ENUM('electric_bill','medical_abstract','hospital_bill','prescription','death_certificate','enrollment_form','child_id','birth_certificate') NOT NULL,
    file_path VARCHAR(255) NOT NULL,
    uploaded_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (request_id) REFERENCES basics_benefit_requests(id) ON DELETE CASCADE
) ENGINE=InnoDB;

-- Where a member's benefit payouts (and other receivables) get sent.
-- One record per member, self-service, editable any time.
CREATE TABLE basics_payout_accounts (
    id INT AUTO_INCREMENT PRIMARY KEY,
    member_id INT NOT NULL UNIQUE,
    method ENUM('gotyme','gcash','bank') NOT NULL,
    bank_name VARCHAR(100) DEFAULT NULL,
    account_name VARCHAR(150) NOT NULL,
    account_number VARCHAR(50) NOT NULL,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (member_id) REFERENCES basics_members(id) ON DELETE CASCADE
) ENGINE=InnoDB;

INSERT INTO settings (setting_key, setting_value) VALUES
('basics_late_penalty_tier1', '0.03'),
('basics_late_penalty_tier2', '0.05'),
('basics_late_penalty_tier3', '0.05'),
('basics_grace_period_days', '7'),
('basics_dormancy_weeks', '3');

-- Sari-sari-store masterlist seed — 613 SKUs across 8 categories.
-- srp is the low end of each masterlist's price range; admin adjusts per item.
INSERT INTO basics_products (sku, category, name, unit, srp) VALUES
('BPC001','Bath & Personal Care','Safeguard Classic White','60g',20),
('BPC002','Bath & Personal Care','Safeguard Classic White','90g',30),
('BPC003','Bath & Personal Care','Safeguard Pure White','60g',20),
('BPC004','Bath & Personal Care','Safeguard Floral Pink','60g',20),
('BPC005','Bath & Personal Care','Safeguard Lemon Fresh','60g',20),
('BPC006','Bath & Personal Care','Safeguard Cool Menthol','60g',20),
('BPC007','Bath & Personal Care','Bioderm Germicidal Soap','60g',15),
('BPC008','Bath & Personal Care','Bioderm Germicidal Soap','90g',20),
('BPC009','Bath & Personal Care','Silka Papaya Soap','65g',18),
('BPC010','Bath & Personal Care','Silka Green Papaya Soap','65g',18),
('BPC011','Bath & Personal Care','Silka Whitening Soap','65g',18),
('BPC012','Bath & Personal Care','Kojic Acid Soap','65g',20),
('BPC013','Bath & Personal Care','Palmolive Naturals Soap','90g',25),
('BPC014','Bath & Personal Care','Palmolive Men Soap','90g',25),
('BPC015','Bath & Personal Care','Lux Soft Touch Soap','90g',25),
('BPC016','Bath & Personal Care','Cream Silk Soap','90g',25),
('BPC017','Bath & Personal Care','Dove Beauty Bar','90g',45),
('BPC018','Bath & Personal Care','Johnson\'s Baby Soap','60g',25),
('BPC019','Bath & Personal Care','Johnson\'s Baby Soap','100g',35),
('BPC020','Bath & Personal Care','Perla Laundry Soap','50g',12),
('BPC021','Bath & Personal Care','Head & Shoulders Shampoo Sachet','12ml',7),
('BPC022','Bath & Personal Care','Head & Shoulders Shampoo Sachet','24ml',12),
('BPC023','Bath & Personal Care','Head & Shoulders Shampoo','170ml',100),
('BPC024','Bath & Personal Care','Pantene Shampoo Sachet','12ml',7),
('BPC025','Bath & Personal Care','Pantene Shampoo Sachet','24ml',12),
('BPC026','Bath & Personal Care','Pantene Shampoo','170ml',100),
('BPC027','Bath & Personal Care','Sunsilk Shampoo Sachet','12ml',7),
('BPC028','Bath & Personal Care','Sunsilk Shampoo Sachet','24ml',12),
('BPC029','Bath & Personal Care','Sunsilk Shampoo','170ml',80),
('BPC030','Bath & Personal Care','Cream Silk Shampoo Sachet','12ml',7),
('BPC031','Bath & Personal Care','Cream Silk Shampoo Sachet','24ml',12),
('BPC032','Bath & Personal Care','Cream Silk Shampoo','170ml',80),
('BPC033','Bath & Personal Care','Rejoice Shampoo Sachet','12ml',7),
('BPC034','Bath & Personal Care','Rejoice Shampoo Sachet','24ml',12),
('BPC035','Bath & Personal Care','Rejoice Shampoo','170ml',80),
('BPC036','Bath & Personal Care','Palmolive Shampoo Sachet','12ml',6),
('BPC037','Bath & Personal Care','Palmolive Shampoo Sachet','24ml',11),
('BPC038','Bath & Personal Care','Palmolive Shampoo','180ml',70),
('BPC039','Bath & Personal Care','Clear Shampoo Sachet','12ml',7),
('BPC040','Bath & Personal Care','Clear Shampoo Sachet','24ml',12),
('BPC041','Bath & Personal Care','Clear Shampoo','170ml',90),
('BPC042','Bath & Personal Care','Head & Shoulders Conditioner Sachet','12ml',7),
('BPC043','Bath & Personal Care','Cream Silk Conditioner Sachet','12ml',7),
('BPC044','Bath & Personal Care','Cream Silk Conditioner Sachet','24ml',12),
('BPC045','Bath & Personal Care','Cream Silk Conditioner','170ml',80),
('BPC046','Bath & Personal Care','Sunsilk Conditioner Sachet','12ml',7),
('BPC047','Bath & Personal Care','Rejoice Conditioner Sachet','12ml',7),
('BPC048','Bath & Personal Care','Colgate Strong Teeth','10ml',7),
('BPC049','Bath & Personal Care','Colgate Strong Teeth','20ml',12),
('BPC050','Bath & Personal Care','Colgate Strong Teeth','40g',25),
('BPC051','Bath & Personal Care','Colgate Strong Teeth','80g',50),
('BPC052','Bath & Personal Care','Closeup Red Hot','20g',12),
('BPC053','Bath & Personal Care','Closeup Red Hot','40g',25),
('BPC054','Bath & Personal Care','Closeup Red Hot','80g',45),
('BPC055','Bath & Personal Care','Hapee Toothpaste','25g',10),
('BPC056','Bath & Personal Care','Hapee Toothpaste','50g',20),
('BPC057','Bath & Personal Care','Hapee Toothpaste','90g',35),
('BPC058','Bath & Personal Care','Hapee Kiddie Toothpaste','50g',20),
('BPC059','Bath & Personal Care','Oral-B Toothpaste','40g',25),
('BPC060','Bath & Personal Care','Oral-B Toothpaste','80g',50),
('BPC061','Bath & Personal Care','Listerine Cool Mint','80ml',40),
('BPC062','Bath & Personal Care','Listerine Cool Mint','250ml',100),
('BPC063','Bath & Personal Care','Colgate Plax Mouthwash','100ml',45),
('BPC064','Bath & Personal Care','Cream Silk Body Wash','100ml',30),
('BPC065','Bath & Personal Care','Palmolive Body Wash','100ml',30),
('BPC066','Bath & Personal Care','Safeguard Body Wash','100ml',35),
('BPC067','Bath & Personal Care','Silka Papaya Body Wash','100ml',30),
('BPC068','Bath & Personal Care','Nivea Body Lotion','50ml',35),
('BPC069','Bath & Personal Care','Nivea Body Lotion','100ml',70),
('BPC070','Bath & Personal Care','Vaseline Lotion','50ml',35),
('BPC071','Bath & Personal Care','Vaseline Lotion','100ml',70),
('BPC072','Bath & Personal Care','Jergens Lotion','100ml',70),
('BPC073','Bath & Personal Care','Rexona Deodorant Sachet/Roll-On','10ml',20),
('BPC074','Bath & Personal Care','Rexona Roll-On','25ml',45),
('BPC075','Bath & Personal Care','Nivea Deodorant Roll-On','25ml',50),
('BPC076','Bath & Personal Care','Milcu Powder','50g',35),
('BPC077','Bath & Personal Care','Milcu Powder','100g',65),
('BPC078','Bath & Personal Care','Baby Bench Cologne','100ml',45),
('BPC079','Bath & Personal Care','Johnson\'s Baby Cologne','100ml',60),
('BPC080','Bath & Personal Care','Johnson\'s Baby Powder','50g',35),
('BPC081','Bath & Personal Care','Johnson\'s Baby Powder','100g',60),
('BPC082','Bath & Personal Care','Cream Silk Hair Treatment Sachet','20ml',15),
('BPC083','Bath & Personal Care','Palmolive Naturals Conditioner','12ml',7),
('BPC084','Bath & Personal Care','Safeguard Hand Soap','200ml',50),
('BPC085','Bath & Personal Care','Bioderm Liquid Hand Soap','200ml',40),
('CG001','Canned Goods','Century Tuna Flakes in Oil','155g',40),
('CG002','Canned Goods','Century Tuna Flakes in Oil','180g',48),
('CG003','Canned Goods','Mega Sardines Tomato Sauce','155g',25),
('CG004','Canned Goods','Ligo Sardines Tomato Sauce','155g',28),
('CG005','Canned Goods','Young\'s Town Sardines Tomato Sauce','155g',25),
('CG006','Canned Goods','555 Sardines Tomato Sauce','155g',28),
('CG007','Canned Goods','Mega Sardines Chili','155g',25),
('CG008','Canned Goods','Ligo Sardines Chili','155g',28),
('CG009','Canned Goods','555 Sardines Chili','155g',28),
('CG010','Canned Goods','Century Tuna Hot & Spicy','155g',40),
('CG011','Canned Goods','Century Tuna Hot & Spicy','180g',48),
('CG012','Canned Goods','Mega Tuna Flakes','155g',35),
('CG013','Canned Goods','Mega Tuna Flakes','180g',40),
('CG014','Canned Goods','San Marino Tuna Flakes','155g',35),
('CG015','Canned Goods','San Marino Tuna Flakes','180g',40),
('CG016','Canned Goods','Argentina Corned Beef','100g',35),
('CG017','Canned Goods','Argentina Corned Beef','150g',50),
('CG018','Canned Goods','Argentina Corned Beef','175g',55),
('CG019','Canned Goods','Highlands Corned Beef','150g',65),
('CG020','Canned Goods','Highlands Corned Beef','175g',70),
('CG021','Canned Goods','Delimondo Corned Beef','175g',90),
('CG022','Canned Goods','Purefoods Corned Beef','150g',55),
('CG023','Canned Goods','Purefoods Corned Beef','210g',75),
('CG024','Canned Goods','Purefoods Corned Beef','340g',115),
('CG025','Canned Goods','CDO Karne Norte','100g',25),
('CG026','Canned Goods','CDO Karne Norte','150g',35),
('CG027','Canned Goods','CDO Karne Norte','175g',40),
('CG028','Canned Goods','Argentina Meat Loaf','100g',25),
('CG029','Canned Goods','Argentina Meat Loaf','150g',35),
('CG030','Canned Goods','CDO Meat Loaf','100g',25),
('CG031','Canned Goods','CDO Meat Loaf','150g',35),
('CG032','Canned Goods','Purefoods Meat Loaf','100g',35),
('CG033','Canned Goods','Purefoods Meat Loaf','150g',45),
('CG034','Canned Goods','Purefoods Meat Loaf','340g',90),
('CG035','Canned Goods','CDO Vienna Sausage','130g',35),
('CG036','Canned Goods','Purefoods Vienna Sausage','130g',45),
('CG037','Canned Goods','Highlands Vienna Sausage','130g',50),
('CG038','Canned Goods','Argentina Vienna Sausage','175g',45),
('CG039','Canned Goods','Young\'s Town Vienna Sausage','130g',35),
('CG040','Canned Goods','Purefoods Luncheon Meat','340g',95),
('CG041','Canned Goods','CDO Luncheon Meat','340g',75),
('CG042','Canned Goods','Argentina Luncheon Meat','340g',65),
('CG043','Canned Goods','Holiday Luncheon Meat','340g',85),
('CG044','Canned Goods','Ligo Mackerel','155g',28),
('CG045','Canned Goods','Mega Mackerel','155g',25),
('CG046','Canned Goods','555 Mackerel','155g',28),
('CG047','Canned Goods','Young\'s Town Mackerel','155g',25),
('CG048','Canned Goods','Ligo Sardines with Egg','155g',30),
('CG049','Canned Goods','555 Sardines with Tausi','155g',30),
('CG050','Canned Goods','Mega Sardines with Tausi','155g',27),
('CG051','Canned Goods','Argentina Beef Loaf','100g',28),
('CG052','Canned Goods','Argentina Beef Loaf','150g',38),
('CG053','Canned Goods','CDO Meat Loaf','340g',75),
('CG054','Canned Goods','Argentina Meat Loaf','340g',70),
('CG055','Canned Goods','Highlands Meat Loaf','100g',40),
('CG056','Canned Goods','Highlands Meat Loaf','150g',50),
('CG057','Canned Goods','Century Corned Tuna','180g',45),
('CG058','Canned Goods','Century Bangus in Oil','155g',45),
('CG059','Canned Goods','Mega Bangus','155g',35),
('CG060','Canned Goods','Ligo Bangus','155g',40),
('CG061','Canned Goods','555 Bangus','155g',40),
('CG062','Canned Goods','Argentina Beef Loaf with Meat','100g',30),
('CG063','Canned Goods','Purefoods Chinese Style Luncheon Meat','340g',100),
('CG064','Canned Goods','CDO Karne Norte with Beans','100g',25),
('CG065','Canned Goods','Argentina Corned Beef with Chili','150g',50),
('CG066','Canned Goods','Argentina Corned Beef','260g',75),
('CG067','Canned Goods','Purefoods Corned Beef','380g',125),
('CG068','Canned Goods','Century Tuna Flakes Hot & Spicy','155g',40),
('CG069','Canned Goods','San Marino Tuna Chili','180g',40),
('CG070','Canned Goods','Mega Tuna Afritada','155g',35),
('CCM001','Coffee, Creamer, Milk & Choco Powder','Café Puro Black Coffee Stick','2g',4),
('CCM002','Coffee, Creamer, Milk & Choco Powder','Nescafé Classic Stick','1.8g',5),
('CCM003','Coffee, Creamer, Milk & Choco Powder','Café Puro 3-in-1','17g',5),
('CCM004','Coffee, Creamer, Milk & Choco Powder','Blend 45 3-in-1 Original','18g',5),
('CCM005','Coffee, Creamer, Milk & Choco Powder','San Mig Coffee Original 3-in-1','20g',7),
('CCM006','Coffee, Creamer, Milk & Choco Powder','Nescafé Original 3-in-1','26g',8),
('CCM007','Coffee, Creamer, Milk & Choco Powder','Nescafé Creamy White','20g',9),
('CCM008','Coffee, Creamer, Milk & Choco Powder','Kopiko Brown','25g',8),
('CCM009','Coffee, Creamer, Milk & Choco Powder','Kopiko Black','30g',8),
('CCM010','Coffee, Creamer, Milk & Choco Powder','Kopiko Blanca','30g',9),
('CCM011','Coffee, Creamer, Milk & Choco Powder','Kopiko L.A. Coffee','25g',9),
('CCM012','Coffee, Creamer, Milk & Choco Powder','Great Taste Original','30g',8),
('CCM013','Coffee, Creamer, Milk & Choco Powder','Great Taste White','30g',9),
('CCM014','Coffee, Creamer, Milk & Choco Powder','Great Taste Choco','30g',9),
('CCM015','Coffee, Creamer, Milk & Choco Powder','San Mig Barako','20g',8),
('CCM016','Coffee, Creamer, Milk & Choco Powder','Nescafé Original Twin Pack','40g',14),
('CCM017','Coffee, Creamer, Milk & Choco Powder','Nescafé Creamy White Twin Pack','40g',14),
('CCM018','Coffee, Creamer, Milk & Choco Powder','Kopiko Brown Twin Pack','50-56g',15),
('CCM019','Coffee, Creamer, Milk & Choco Powder','Kopiko Black Twin Pack','50-56g',15),
('CCM020','Coffee, Creamer, Milk & Choco Powder','Great Taste Original Twin Pack','~50g',10),
('CCM021','Coffee, Creamer, Milk & Choco Powder','Great Taste White Twin Pack','~50g',13),
('CCM022','Coffee, Creamer, Milk & Choco Powder','San Mig Super Coffee Twin Pack','~40g',14),
('CCM023','Coffee, Creamer, Milk & Choco Powder','Great Taste Premium Trio','~50g',13),
('CCM024','Coffee, Creamer, Milk & Choco Powder','Nescafé Original','50g',110),
('CCM025','Coffee, Creamer, Milk & Choco Powder','Great Taste Premium','50g',40),
('CCM026','Coffee, Creamer, Milk & Choco Powder','Great Taste Granules','50g',40),
('CCM027','Coffee, Creamer, Milk & Choco Powder','Krem-Top Coffee Creamer','20g',7),
('CCM028','Coffee, Creamer, Milk & Choco Powder','Birch Tree Coffee Creamer','25g',10),
('CCM029','Coffee, Creamer, Milk & Choco Powder','Coffee-Mate','150g',50),
('CCM030','Coffee, Creamer, Milk & Choco Powder','Krem-Top Coffee Creamer','170g',50),
('CCM031','Coffee, Creamer, Milk & Choco Powder','Coffee-Mate','220g',70),
('CCM032','Coffee, Creamer, Milk & Choco Powder','Coffee-Mate','250g',80),
('CCM033','Coffee, Creamer, Milk & Choco Powder','Krem-Top Coffee Creamer','250g',60),
('CCM034','Coffee, Creamer, Milk & Choco Powder','Coffee-Mate','400g',120),
('CCM035','Coffee, Creamer, Milk & Choco Powder','Krem-Top Coffee Creamer','450g',110),
('CCM036','Coffee, Creamer, Milk & Choco Powder','Alaska Fortified Milk','33g',9),
('CCM037','Coffee, Creamer, Milk & Choco Powder','Bear Brand Fortified','33g',10),
('CCM038','Coffee, Creamer, Milk & Choco Powder','Birch Tree Fortified Milk','33g',10),
('CCM039','Coffee, Creamer, Milk & Choco Powder','Bear Brand Chocolate','29g',13),
('CCM040','Coffee, Creamer, Milk & Choco Powder','Alaska Fortified Milk Twin/Multipack','6x33g',48),
('CCM041','Coffee, Creamer, Milk & Choco Powder','Birch Tree Fortified Milk','10x33g',100),
('CCM042','Coffee, Creamer, Milk & Choco Powder','Bear Brand Fortified','150g',55),
('CCM043','Coffee, Creamer, Milk & Choco Powder','Alaska Powdered Milk','150g',50),
('CCM044','Coffee, Creamer, Milk & Choco Powder','Nido Fortified','150g',70),
('CCM045','Coffee, Creamer, Milk & Choco Powder','Bear Brand Fortified','300g',110),
('CCM046','Coffee, Creamer, Milk & Choco Powder','Alaska Powdered Milk','300g',100),
('CCM047','Coffee, Creamer, Milk & Choco Powder','Nido Fortified','300g',140),
('CCM048','Coffee, Creamer, Milk & Choco Powder','MILO Activ-Go','24g',9),
('CCM049','Coffee, Creamer, Milk & Choco Powder','MILO Twin Pack','48g',17),
('CCM050','Coffee, Creamer, Milk & Choco Powder','Ovaltine All-In-One','20g',10),
('CCM051','Coffee, Creamer, Milk & Choco Powder','Ovaltine Premium Malt','25g',10),
('CCM052','Coffee, Creamer, Milk & Choco Powder','Energen Chocolate','~30g',10),
('CCM053','Coffee, Creamer, Milk & Choco Powder','Ovaltine All-In-One','20g x10',105),
('CCM054','Coffee, Creamer, Milk & Choco Powder','MILO','150g',50),
('CCM055','Coffee, Creamer, Milk & Choco Powder','Ovaltine Premium Malt','450g',350),
('CCM056','Coffee, Creamer, Milk & Choco Powder','MILO','300g',100),
('CCM057','Coffee, Creamer, Milk & Choco Powder','MILO','600g',190),
('CCM058','Coffee, Creamer, Milk & Choco Powder','MILO','1kg',300),
('CCM059','Coffee, Creamer, Milk & Choco Powder','Ovaltine All-In-One','840g',310),
('CCM060','Coffee, Creamer, Milk & Choco Powder','Swiss Miss Chocolate Drink','~25g',20),
('CCM061','Coffee, Creamer, Milk & Choco Powder','Ricoa Cocoa Powder','~25g',15),
('CCM062','Coffee, Creamer, Milk & Choco Powder','Hershey\'s Cocoa','Small Pack',20),
('CCM063','Coffee, Creamer, Milk & Choco Powder','Cadbury Drinking Chocolate','Small Pack',20),
('CCM064','Coffee, Creamer, Milk & Choco Powder','Energen Vanilla','~30g',10),
('CCM065','Coffee, Creamer, Milk & Choco Powder','Energen Cereal Milk','~30g',10),
('CCM066','Coffee, Creamer, Milk & Choco Powder','Bear Brand Busog Lusog','Sachet',10),
('CCM067','Coffee, Creamer, Milk & Choco Powder','MILO','500g',160),
('CCM068','Coffee, Creamer, Milk & Choco Powder','MILO','900g-1kg',290),
('INC001','Instant Noodles & Cup Noodles','Lucky Me! Pancit Canton Original','60g',15),
('INC002','Instant Noodles & Cup Noodles','Lucky Me! Pancit Canton Chilimansi','60g',15),
('INC003','Instant Noodles & Cup Noodles','Lucky Me! Pancit Canton Calamansi','60g',15),
('INC004','Instant Noodles & Cup Noodles','Lucky Me! Pancit Canton Sweet & Spicy','60g',15),
('INC005','Instant Noodles & Cup Noodles','Lucky Me! Beef Mami','55g',12),
('INC006','Instant Noodles & Cup Noodles','Lucky Me! Chicken Mami','55g',12),
('INC007','Instant Noodles & Cup Noodles','Lucky Me! Batchoy','55g',12),
('INC008','Instant Noodles & Cup Noodles','Lucky Me! Bulalo','55g',12),
('INC009','Instant Noodles & Cup Noodles','Lucky Me! La Paz Batchoy','55g',12),
('INC010','Instant Noodles & Cup Noodles','Lucky Me! Special Beef','55g',12),
('INC011','Instant Noodles & Cup Noodles','Lucky Me! Special Chicken','55g',12),
('INC012','Instant Noodles & Cup Noodles','Payless Pancit Canton Original','60g',12),
('INC013','Instant Noodles & Cup Noodles','Payless Pancit Canton Sweet & Spicy','60g',12),
('INC014','Instant Noodles & Cup Noodles','Payless Xtra Big Pancit Canton Original','120g',25),
('INC015','Instant Noodles & Cup Noodles','Payless Xtra Big Pancit Canton Sweet & Spicy','120g',25),
('INC016','Instant Noodles & Cup Noodles','Payless Instant Mami Chicken','50g',10),
('INC017','Instant Noodles & Cup Noodles','Payless Instant Mami Beef','50g',10),
('INC018','Instant Noodles & Cup Noodles','Payless Instant Mami Bulalo','50g',10),
('INC019','Instant Noodles & Cup Noodles','Ho-Mi Instant Mami Chicken','60g',10),
('INC020','Instant Noodles & Cup Noodles','Ho-Mi Instant Mami Beef','60g',10),
('INC021','Instant Noodles & Cup Noodles','Ho-Mi Instant Mami Seafood','60g',10),
('INC022','Instant Noodles & Cup Noodles','Nissin Yakisoba Original','55g',15),
('INC023','Instant Noodles & Cup Noodles','Nissin Yakisoba Spicy Chicken','55g',15),
('INC024','Instant Noodles & Cup Noodles','Nissin Ramen Beef','55g',13),
('INC025','Instant Noodles & Cup Noodles','Nissin Ramen Chicken','55g',13),
('INC026','Instant Noodles & Cup Noodles','Nissin Ramen Seafood','55g',13),
('INC027','Instant Noodles & Cup Noodles','Nissin Cup Noodles Beef','40-45g',30),
('INC028','Instant Noodles & Cup Noodles','Nissin Cup Noodles Chicken','40-45g',30),
('INC029','Instant Noodles & Cup Noodles','Nissin Cup Noodles Seafood','40-45g',30),
('INC030','Instant Noodles & Cup Noodles','Nissin Cup Noodles Spicy Seafood','40-45g',30),
('INC031','Instant Noodles & Cup Noodles','Lucky Me! Go Cup Beef','~50g',25),
('INC032','Instant Noodles & Cup Noodles','Lucky Me! Go Cup Chicken','~50g',25),
('INC033','Instant Noodles & Cup Noodles','Lucky Me! Go Cup Bulalo','~50g',25),
('INC034','Instant Noodles & Cup Noodles','Payless Instant Mami Cup Chicken','~50g',20),
('INC035','Instant Noodles & Cup Noodles','Payless Instant Mami Cup Beef','~50g',20),
('INC036','Instant Noodles & Cup Noodles','Payless Instant Mami Cup Bulalo','~50g',20),
('INC037','Instant Noodles & Cup Noodles','Payless Big Instant Noodles','~100g',20),
('INC038','Instant Noodles & Cup Noodles','Payless Xtra Big Instant Noodles','~120g',25),
('INC039','Instant Noodles & Cup Noodles','Maggi Kari Instant Noodles','~60g',12),
('INC040','Instant Noodles & Cup Noodles','Maggi Chicken Instant Noodles','~60g',12),
('INC041','Instant Noodles & Cup Noodles','Maggi Beef Instant Noodles','~60g',12),
('INC042','Instant Noodles & Cup Noodles','Maggi Kari Cup Noodles','~60g',25),
('INC043','Instant Noodles & Cup Noodles','Samyang Buldak Original','140g',65),
('INC044','Instant Noodles & Cup Noodles','Samyang Buldak Carbonara','130g',70),
('INC045','Instant Noodles & Cup Noodles','Samyang Buldak Cheese','140g',65),
('INC046','Instant Noodles & Cup Noodles','Samyang Buldak 2X Spicy','140g',70),
('INC047','Instant Noodles & Cup Noodles','Nongshim Shin Ramyun','120g',55),
('INC048','Instant Noodles & Cup Noodles','Nongshim Shin Cup','68g',45),
('INC049','Instant Noodles & Cup Noodles','Nongshim Neoguri','120g',55),
('INC050','Instant Noodles & Cup Noodles','Nongshim Chapagetti','140g',55),
('INC051','Instant Noodles & Cup Noodles','Indomie Mi Goreng Original','80g',15),
('INC052','Instant Noodles & Cup Noodles','Indomie Mi Goreng Hot & Spicy','80g',15),
('INC053','Instant Noodles & Cup Noodles','Indomie Mi Goreng Rendang','91g',18),
('INC054','Instant Noodles & Cup Noodles','Indomie Chicken Flavor','70g',15),
('INC055','Instant Noodles & Cup Noodles','Indomie Mi Goreng Cup','~75g',30),
('INC056','Instant Noodles & Cup Noodles','Lucky Me! Supreme','~55g',15),
('INC057','Instant Noodles & Cup Noodles','Lucky Me! Supreme Beef Cup','~60g',30),
('INC058','Instant Noodles & Cup Noodles','Lucky Me! Supreme Chicken Cup','~60g',30),
('INC059','Instant Noodles & Cup Noodles','Nissin Seafood Cup Noodles','~40g',30),
('INC060','Instant Noodles & Cup Noodles','Nissin Spicy Seafood Cup Noodles','~40g',30),
('KCS001','Kitchen Condiments & Seasonings','Iodized Salt','250g',8),
('KCS002','Kitchen Condiments & Seasonings','Iodized Salt','500g',15),
('KCS003','Kitchen Condiments & Seasonings','Iodized Salt','1kg',25),
('KCS004','Kitchen Condiments & Seasonings','Datu Puti Soy Sauce','200ml',12),
('KCS005','Kitchen Condiments & Seasonings','Datu Puti Soy Sauce','385ml',22),
('KCS006','Kitchen Condiments & Seasonings','Datu Puti Soy Sauce','1L',45),
('KCS007','Kitchen Condiments & Seasonings','Silver Swan Soy Sauce','200ml',12),
('KCS008','Kitchen Condiments & Seasonings','Silver Swan Soy Sauce','385ml',22),
('KCS009','Kitchen Condiments & Seasonings','Silver Swan Soy Sauce','1L',45),
('KCS010','Kitchen Condiments & Seasonings','Datu Puti Vinegar','200ml',12),
('KCS011','Kitchen Condiments & Seasonings','Datu Puti Vinegar','385ml',20),
('KCS012','Kitchen Condiments & Seasonings','Datu Puti Vinegar','1L',40),
('KCS013','Kitchen Condiments & Seasonings','Sukang Tunay Vinegar','350ml',20),
('KCS014','Kitchen Condiments & Seasonings','Silver Swan Vinegar','350ml',20),
('KCS015','Kitchen Condiments & Seasonings','Silver Swan Vinegar','1L',40),
('KCS016','Kitchen Condiments & Seasonings','Datu Puti Patis','200ml',15),
('KCS017','Kitchen Condiments & Seasonings','Datu Puti Patis','385ml',25),
('KCS018','Kitchen Condiments & Seasonings','Datu Puti Patis','1L',50),
('KCS019','Kitchen Condiments & Seasonings','Marca Piña Patis','200ml',15),
('KCS020','Kitchen Condiments & Seasonings','Marca Piña Patis','385ml',25),
('KCS021','Kitchen Condiments & Seasonings','UFC Banana Catsup','200g',18),
('KCS022','Kitchen Condiments & Seasonings','UFC Banana Catsup','320g',30),
('KCS023','Kitchen Condiments & Seasonings','UFC Banana Catsup','567g',50),
('KCS024','Kitchen Condiments & Seasonings','Jufran Banana Sauce','200g',18),
('KCS025','Kitchen Condiments & Seasonings','Jufran Banana Sauce','320g',28),
('KCS026','Kitchen Condiments & Seasonings','Datu Puti Premium Patis','350ml',25),
('KCS027','Kitchen Condiments & Seasonings','Mang Tomas All-Around Sarsa','330ml',35),
('KCS028','Kitchen Condiments & Seasonings','Mang Tomas All-Around Sarsa','550ml',50),
('KCS029','Kitchen Condiments & Seasonings','UFC Tomato Ketchup','200g',20),
('KCS030','Kitchen Condiments & Seasonings','UFC Tomato Ketchup','320g',30),
('KCS031','Kitchen Condiments & Seasonings','UFC Tomato Ketchup','567g',50),
('KCS032','Kitchen Condiments & Seasonings','Del Monte Tomato Ketchup','200g',20),
('KCS033','Kitchen Condiments & Seasonings','Del Monte Tomato Ketchup','320g',30),
('KCS034','Kitchen Condiments & Seasonings','Del Monte Tomato Ketchup','567g',50),
('KCS035','Kitchen Condiments & Seasonings','Jufran Tomato Ketchup','200g',20),
('KCS036','Kitchen Condiments & Seasonings','Jufran Tomato Ketchup','320g',30),
('KCS037','Kitchen Condiments & Seasonings','Mama Sita\'s Sinigang sa Sampalok Mix','20g',10),
('KCS038','Kitchen Condiments & Seasonings','Knorr Sinigang sa Sampalok Mix','20g',10),
('KCS039','Kitchen Condiments & Seasonings','Knorr Sinigang sa Sampalok Mix','44g',18),
('KCS040','Kitchen Condiments & Seasonings','Knorr Sinigang sa Sampalok Mix','50g',20),
('KCS041','Kitchen Condiments & Seasonings','Mama Sita\'s Sinigang sa Sampalok Mix','40g',18),
('KCS042','Kitchen Condiments & Seasonings','Mama Sita\'s Sinigang sa Sampalok Mix','50g',20),
('KCS043','Kitchen Condiments & Seasonings','Knorr Chicken Broth Cube','10g',7),
('KCS044','Kitchen Condiments & Seasonings','Knorr Beef Broth Cube','10g',7),
('KCS045','Kitchen Condiments & Seasonings','Knorr Pork Broth Cube','10g',7),
('KCS046','Kitchen Condiments & Seasonings','Knorr Shrimp Broth Cube','10g',7),
('KCS047','Kitchen Condiments & Seasonings','Maggi Magic Sarap','8g',4),
('KCS048','Kitchen Condiments & Seasonings','Maggi Magic Sarap','50g',25),
('KCS049','Kitchen Condiments & Seasonings','Maggi Magic Sarap','100g',45),
('KCS050','Kitchen Condiments & Seasonings','Maggi Magic Sarap','120g',55),
('KCS051','Kitchen Condiments & Seasonings','Knorr Sinigang sa Sampalok with Gabi','40g',18),
('KCS052','Kitchen Condiments & Seasonings','Knorr Ginataang Gulay Mix','40g',18),
('KCS053','Kitchen Condiments & Seasonings','Knorr Ginataang Manok Mix','40g',18),
('KCS054','Kitchen Condiments & Seasonings','Knorr Kare-Kare Mix','50g',20),
('KCS055','Kitchen Condiments & Seasonings','Mama Sita\'s Kare-Kare Mix','50g',20),
('KCS056','Kitchen Condiments & Seasonings','Mama Sita\'s Caldereta Mix','50g',20),
('KCS057','Kitchen Condiments & Seasonings','Mama Sita\'s Menudo Mix','50g',20),
('KCS058','Kitchen Condiments & Seasonings','Mama Sita\'s Afritada Mix','50g',20),
('KCS059','Kitchen Condiments & Seasonings','Mama Sita\'s Adobo Mix','50g',20),
('KCS060','Kitchen Condiments & Seasonings','Mama Sita\'s Palabok Mix','57g',20),
('KCS061','Kitchen Condiments & Seasonings','Knorr Ginataang Gulay Recipe Mix','40g',18),
('KCS062','Kitchen Condiments & Seasonings','Knorr Kare-Kare Recipe Mix','50g',20),
('KCS063','Kitchen Condiments & Seasonings','Knorr Caldereta Recipe Mix','50g',20),
('KCS064','Kitchen Condiments & Seasonings','Knorr Menudo Recipe Mix','50g',20),
('KCS065','Kitchen Condiments & Seasonings','Knorr Afritada Recipe Mix','50g',20),
('KCS066','Kitchen Condiments & Seasonings','Knorr Sinigang Mix','22g',10),
('KCS067','Kitchen Condiments & Seasonings','Knorr Liquid Seasoning','130ml',35),
('KCS068','Kitchen Condiments & Seasonings','Maggi Savor Classic','130ml',30),
('KCS069','Kitchen Condiments & Seasonings','Maggi Savor Calamansi','130ml',30),
('KCS070','Kitchen Condiments & Seasonings','Datu Puti Chili Garlic Sauce','100ml',20),
('KCS071','Kitchen Condiments & Seasonings','Datu Puti Hot & Spicy Vinegar','350ml',20),
('KCS072','Kitchen Condiments & Seasonings','UFC Hot & Spicy Banana Catsup','200g',20),
('KCS073','Kitchen Condiments & Seasonings','UFC Sweet Chili Sauce','200ml',30),
('KCS074','Kitchen Condiments & Seasonings','Jufran Sweet Chili Sauce','200ml',30),
('KCS075','Kitchen Condiments & Seasonings','Mama Sita\'s Oyster Sauce','150ml',30),
('KCS076','Kitchen Condiments & Seasonings','Datu Puti Oyster Sauce','155ml',25),
('KCS077','Kitchen Condiments & Seasonings','Lee Kum Kee Oyster Sauce','255g',80),
('KCS078','Kitchen Condiments & Seasonings','Lady\'s Choice Mayonnaise','80ml',20),
('KCS079','Kitchen Condiments & Seasonings','Lady\'s Choice Mayonnaise','220ml',55),
('KCS080','Kitchen Condiments & Seasonings','Lady\'s Choice Mayonnaise','470ml',100),
('KCS081','Kitchen Condiments & Seasonings','Best Foods Mayonnaise','220ml',55),
('KCS082','Kitchen Condiments & Seasonings','UFC Mayonnaise','220ml',45),
('KCS083','Kitchen Condiments & Seasonings','UFC Tomato Sauce','115g',15),
('KCS084','Kitchen Condiments & Seasonings','Del Monte Tomato Sauce','115g',15),
('KCS085','Kitchen Condiments & Seasonings','Del Monte Tomato Sauce','250g',25),
('KCS086','Kitchen Condiments & Seasonings','Del Monte Tomato Sauce','500g',45),
('KCS087','Kitchen Condiments & Seasonings','Del Monte Spaghetti Sauce','250g',30),
('KCS088','Kitchen Condiments & Seasonings','Del Monte Spaghetti Sauce','500g',55),
('KCS089','Kitchen Condiments & Seasonings','UFC Spaghetti Sauce','250g',25),
('KCS090','Kitchen Condiments & Seasonings','UFC Spaghetti Sauce','500g',45),
('LCN001','Laundry & Cleaning Needs','Surf Powder Detergent','20g',7),
('LCN002','Laundry & Cleaning Needs','Surf Powder Detergent','40g',12),
('LCN003','Laundry & Cleaning Needs','Surf Powder Detergent','66g',18),
('LCN004','Laundry & Cleaning Needs','Surf Powder Detergent','100g',25),
('LCN005','Laundry & Cleaning Needs','Surf Powder Detergent','500g',70),
('LCN006','Laundry & Cleaning Needs','Ariel Powder Detergent','30g',8),
('LCN007','Laundry & Cleaning Needs','Ariel Powder Detergent','66g',18),
('LCN008','Laundry & Cleaning Needs','Ariel Powder Detergent','100g',25),
('LCN009','Laundry & Cleaning Needs','Ariel Powder Detergent','500g',75),
('LCN010','Laundry & Cleaning Needs','Tide Powder Detergent','40g',10),
('LCN011','Laundry & Cleaning Needs','Tide Powder Detergent','66g',18),
('LCN012','Laundry & Cleaning Needs','Tide Powder Detergent','100g',25),
('LCN013','Laundry & Cleaning Needs','Tide Powder Detergent','500g',70),
('LCN014','Laundry & Cleaning Needs','Champion Powder Detergent','40g',7),
('LCN015','Laundry & Cleaning Needs','Champion Powder Detergent','80g',14),
('LCN016','Laundry & Cleaning Needs','Champion Powder Detergent','500g',50),
('LCN017','Laundry & Cleaning Needs','Pride Powder Detergent','40g',7),
('LCN018','Laundry & Cleaning Needs','Pride Powder Detergent','80g',14),
('LCN019','Laundry & Cleaning Needs','Pride Powder Detergent','500g',50),
('LCN020','Laundry & Cleaning Needs','Calla Powder Detergent','40g',7),
('LCN021','Laundry & Cleaning Needs','Calla Powder Detergent','80g',14),
('LCN022','Laundry & Cleaning Needs','Calla Powder Detergent','500g',50),
('LCN023','Laundry & Cleaning Needs','Breeze Powder Detergent','40g',8),
('LCN024','Laundry & Cleaning Needs','Breeze Powder Detergent','66g',17),
('LCN025','Laundry & Cleaning Needs','Breeze Powder Detergent','500g',70),
('LCN026','Laundry & Cleaning Needs','Surf Liquid Detergent','20ml',8),
('LCN027','Laundry & Cleaning Needs','Surf Liquid Detergent','40ml',13),
('LCN028','Laundry & Cleaning Needs','Ariel Liquid Detergent','20ml',8),
('LCN029','Laundry & Cleaning Needs','Ariel Liquid Detergent','40ml',13),
('LCN030','Laundry & Cleaning Needs','Zonrox Bleach','100ml',10),
('LCN031','Laundry & Cleaning Needs','Zonrox Bleach','250ml',20),
('LCN032','Laundry & Cleaning Needs','Zonrox Bleach','500ml',35),
('LCN033','Laundry & Cleaning Needs','Zonrox Bleach','1L',65),
('LCN034','Laundry & Cleaning Needs','Zonrox Color Safe','250ml',25),
('LCN035','Laundry & Cleaning Needs','Zonrox Color Safe','500ml',45),
('LCN036','Laundry & Cleaning Needs','Zonrox Color Safe','1L',80),
('LCN037','Laundry & Cleaning Needs','Domex Toilet Cleaner','50ml',12),
('LCN038','Laundry & Cleaning Needs','Domex Toilet Cleaner','500ml',65),
('LCN039','Laundry & Cleaning Needs','Domex Toilet Cleaner','750ml',85),
('LCN040','Laundry & Cleaning Needs','Mr. Muscle Multi-Purpose Cleaner','250ml',35),
('LCN041','Laundry & Cleaning Needs','Mr. Muscle Multi-Purpose Cleaner','500ml',60),
('LCN042','Laundry & Cleaning Needs','Mr. Muscle Glass Cleaner','500ml',60),
('LCN043','Laundry & Cleaning Needs','Mr. Muscle Bathroom Cleaner','500ml',65),
('LCN044','Laundry & Cleaning Needs','Cif Cream Cleaner','250ml',50),
('LCN045','Laundry & Cleaning Needs','Cif Cream Cleaner','500ml',80),
('LCN046','Laundry & Cleaning Needs','Joy Dishwashing Liquid','20ml',8),
('LCN047','Laundry & Cleaning Needs','Joy Dishwashing Liquid','40ml',13),
('LCN048','Laundry & Cleaning Needs','Joy Dishwashing Liquid','200ml',35),
('LCN049','Laundry & Cleaning Needs','Joy Dishwashing Liquid','500ml',70),
('LCN050','Laundry & Cleaning Needs','Joy Dishwashing Liquid','1L',120),
('LCN051','Laundry & Cleaning Needs','Axion Dishwashing Paste','50g',15),
('LCN052','Laundry & Cleaning Needs','Axion Dishwashing Paste','100g',25),
('LCN053','Laundry & Cleaning Needs','Axion Dishwashing Paste','200g',45),
('LCN054','Laundry & Cleaning Needs','Smart Dishwashing Paste','50g',10),
('LCN055','Laundry & Cleaning Needs','Smart Dishwashing Paste','100g',18),
('LCN056','Laundry & Cleaning Needs','Mr. Clean Dishwashing Liquid','200ml',25),
('LCN057','Laundry & Cleaning Needs','Mr. Clean Dishwashing Liquid','500ml',50),
('LCN058','Laundry & Cleaning Needs','Downy Fabric Conditioner','20ml',8),
('LCN059','Laundry & Cleaning Needs','Downy Fabric Conditioner','40ml',14),
('LCN060','Laundry & Cleaning Needs','Downy Fabric Conditioner','90ml',25),
('LCN061','Laundry & Cleaning Needs','Downy Fabric Conditioner','500ml',75),
('LCN062','Laundry & Cleaning Needs','Downy Fabric Conditioner','1L',130),
('LCN063','Laundry & Cleaning Needs','Surf Fabric Conditioner','20ml',7),
('LCN064','Laundry & Cleaning Needs','Surf Fabric Conditioner','40ml',12),
('LCN065','Laundry & Cleaning Needs','Surf Fabric Conditioner','90ml',20),
('LCN066','Laundry & Cleaning Needs','Surf Fabric Conditioner','500ml',60),
('LCN067','Laundry & Cleaning Needs','Champion Fabric Conditioner','20ml',6),
('LCN068','Laundry & Cleaning Needs','Champion Fabric Conditioner','40ml',10),
('LCN069','Laundry & Cleaning Needs','Champion Fabric Conditioner','500ml',45),
('LCN070','Laundry & Cleaning Needs','Pride Fabric Conditioner','20ml',6),
('LCN071','Laundry & Cleaning Needs','Pride Fabric Conditioner','40ml',10),
('LCN072','Laundry & Cleaning Needs','Pride Fabric Conditioner','500ml',45),
('LCN073','Laundry & Cleaning Needs','Zonrox Colorsafe Fabric Conditioner','500ml',50),
('LCN074','Laundry & Cleaning Needs','Mr. Clean Disinfectant','250ml',25),
('LCN075','Laundry & Cleaning Needs','Mr. Clean Disinfectant','500ml',45),
('LCN076','Laundry & Cleaning Needs','Mr. Muscle Disinfectant','250ml',35),
('LCN077','Laundry & Cleaning Needs','Mr. Muscle Disinfectant','500ml',60),
('LCN078','Laundry & Cleaning Needs','Lysol Disinfectant Spray','100ml',35),
('LCN079','Laundry & Cleaning Needs','Lysol Disinfectant Spray','300ml',90),
('LCN080','Laundry & Cleaning Needs','Lysol Disinfectant Liquid','250ml',35),
('LCN081','Laundry & Cleaning Needs','Lysol Disinfectant Liquid','500ml',60),
('LCN082','Laundry & Cleaning Needs','Zonrox Toilet Cleaner','500ml',45),
('LCN083','Laundry & Cleaning Needs','Harpic Toilet Cleaner','200ml',30),
('LCN084','Laundry & Cleaning Needs','Harpic Toilet Cleaner','500ml',65),
('LCN085','Laundry & Cleaning Needs','Harpic Toilet Cleaner','750ml',85),
('LCN086','Laundry & Cleaning Needs','Mr. Muscle Toilet Cleaner','500ml',60),
('LCN087','Laundry & Cleaning Needs','Pride Bleach','250ml',15),
('LCN088','Laundry & Cleaning Needs','Pride Bleach','500ml',25),
('LCN089','Laundry & Cleaning Needs','Pride Bleach','1L',45),
('LCN090','Laundry & Cleaning Needs','Champion Bleach','250ml',15),
('LCN091','Laundry & Cleaning Needs','Champion Bleach','500ml',25),
('LCN092','Laundry & Cleaning Needs','Champion Bleach','1L',45),
('LCN093','Laundry & Cleaning Needs','Mr. Clean Floor Cleaner','250ml',25),
('LCN094','Laundry & Cleaning Needs','Mr. Clean Floor Cleaner','500ml',45),
('LCN095','Laundry & Cleaning Needs','Mr. Muscle Floor Cleaner','500ml',60),
('LCN096','Laundry & Cleaning Needs','Scotch-Brite Sponge','1pc',15),
('LCN097','Laundry & Cleaning Needs','Scotch-Brite Scrub Sponge','2pcs',30),
('LCN098','Laundry & Cleaning Needs','Scotch-Brite Steel Scrub','1pc',15),
('LCN099','Laundry & Cleaning Needs','Zonrox Dishwashing Liquid','200ml',25),
('LCN100','Laundry & Cleaning Needs','Zonrox Dishwashing Liquid','500ml',50),
('LBC001','Loaf, Biscuits & Crackers','Gardenia Classic White Bread','400g',75),
('LBC002','Loaf, Biscuits & Crackers','Gardenia High Fiber Whole Wheat','400g',85),
('LBC003','Loaf, Biscuits & Crackers','Gardenia Wheat Bread','400g',80),
('LBC004','Loaf, Biscuits & Crackers','Gardenia Chocolate Chip Bread','400g',85),
('LBC005','Loaf, Biscuits & Crackers','Gardenia Pandesal','250g',45),
('LBC006','Loaf, Biscuits & Crackers','Pinoy Tasty','450g',45),
('LBC007','Loaf, Biscuits & Crackers','Pinoy Tasty','600g',55),
('LBC008','Loaf, Biscuits & Crackers','Pinoy Pandesal','250g',35),
('LBC009','Loaf, Biscuits & Crackers','Pinoy Spanish Bread','250g',40),
('LBC010','Loaf, Biscuits & Crackers','Pinoy Chocolate Bread','250g',40),
('LBC011','Loaf, Biscuits & Crackers','Marby Bread','400g',45),
('LBC012','Loaf, Biscuits & Crackers','Marby Wheat Bread','400g',50),
('LBC013','Loaf, Biscuits & Crackers','Pinoy Butter Bread','250g',40),
('LBC014','Loaf, Biscuits & Crackers','SkyFlakes Original Crackers','25g',8),
('LBC015','Loaf, Biscuits & Crackers','SkyFlakes Original Crackers','50g',15),
('LBC016','Loaf, Biscuits & Crackers','SkyFlakes Garlic & Onion','25g',8),
('LBC017','Loaf, Biscuits & Crackers','SkyFlakes Onion & Chives','25g',8),
('LBC018','Loaf, Biscuits & Crackers','SkyFlakes Crackers Sandwich','33g',10),
('LBC019','Loaf, Biscuits & Crackers','Fita Crackers','30g',8),
('LBC020','Loaf, Biscuits & Crackers','Fita Crackers','60g',15),
('LBC021','Loaf, Biscuits & Crackers','Hansel Premium Crackers','32g',9),
('LBC022','Loaf, Biscuits & Crackers','Hansel Chocolate Sandwich','32g',9),
('LBC023','Loaf, Biscuits & Crackers','Hansel Cheese Sandwich','32g',9),
('LBC024','Loaf, Biscuits & Crackers','Hansel Butter Sandwich','32g',9),
('LBC025','Loaf, Biscuits & Crackers','Rebisco Crackers','33g',8),
('LBC026','Loaf, Biscuits & Crackers','Rebisco Honey Butter Crackers','33g',9),
('LBC027','Loaf, Biscuits & Crackers','Rebisco Whole Wheat Crackers','33g',9),
('LBC028','Loaf, Biscuits & Crackers','Rebisco Sandwich Chocolate','33g',9),
('LBC029','Loaf, Biscuits & Crackers','Rebisco Sandwich Peanut Butter','33g',9),
('LBC030','Loaf, Biscuits & Crackers','Rebisco Sandwich Cream','33g',9),
('LBC031','Loaf, Biscuits & Crackers','Cream-O Chocolate Sandwich','33g',9),
('LBC032','Loaf, Biscuits & Crackers','Cream-O Chocolate Sandwich','110g',25),
('LBC033','Loaf, Biscuits & Crackers','Cream-O Vanilla Sandwich','33g',9),
('LBC034','Loaf, Biscuits & Crackers','Oreo Original','27.6g',10),
('LBC035','Loaf, Biscuits & Crackers','Oreo Original','133g',40),
('LBC036','Loaf, Biscuits & Crackers','Oreo Chocolate','133g',40),
('LBC037','Loaf, Biscuits & Crackers','Fibisco Choco Chip Cookies','30g',10),
('LBC038','Loaf, Biscuits & Crackers','Fibisco Marie','30g',8),
('LBC039','Loaf, Biscuits & Crackers','Fibisco Marie','125g',25),
('LBC040','Loaf, Biscuits & Crackers','Fibisco Butter Cookies','100g',25),
('LBC041','Loaf, Biscuits & Crackers','Marie Biscuits','30g',8),
('LBC042','Loaf, Biscuits & Crackers','Marie Biscuits','120g',25),
('LBC043','Loaf, Biscuits & Crackers','Butter Coconut Biscuits','30g',8),
('LBC044','Loaf, Biscuits & Crackers','Butter Coconut Biscuits','100g',20),
('LBC045','Loaf, Biscuits & Crackers','Lemon Square Cheesecake','30g',10),
('LBC046','Loaf, Biscuits & Crackers','Lemon Square Chocolate','30g',10),
('LBC047','Loaf, Biscuits & Crackers','Fudgee Barr Chocolate','38g',10),
('LBC048','Loaf, Biscuits & Crackers','Fudgee Barr Vanilla','38g',10),
('LBC049','Loaf, Biscuits & Crackers','Fudgee Barr Cheese','38g',10),
('LBC050','Loaf, Biscuits & Crackers','Fudgee Barr Chocolate','10x38g',85),
('LBC051','Loaf, Biscuits & Crackers','Magic Flakes Original','25g',8),
('LBC052','Loaf, Biscuits & Crackers','Magic Flakes Garlic','25g',8),
('LBC053','Loaf, Biscuits & Crackers','Magic Flakes Onion','25g',8),
('LBC054','Loaf, Biscuits & Crackers','Magic Flakes Chicken','25g',8),
('LBC055','Loaf, Biscuits & Crackers','Magic Flakes','100g',20),
('LBC056','Loaf, Biscuits & Crackers','Rebisco Crackers','10x33g',85),
('LBC057','Loaf, Biscuits & Crackers','SkyFlakes Crackers','10x25g',80),
('LBC058','Loaf, Biscuits & Crackers','Fita Crackers','10x30g',80),
('LBC059','Loaf, Biscuits & Crackers','Hansel Crackers','10x32g',85),
('LBC060','Loaf, Biscuits & Crackers','Cream-O Sandwich','10x33g',90),
('LBC061','Loaf, Biscuits & Crackers','Oreo Original','10x27.6g',95),
('LBC062','Loaf, Biscuits & Crackers','Bingo Chocolate Sandwich','30g',8),
('LBC063','Loaf, Biscuits & Crackers','Bingo Chocolate Sandwich','110g',25),
('LBC064','Loaf, Biscuits & Crackers','Bingo Vanilla Sandwich','30g',8),
('LBC065','Loaf, Biscuits & Crackers','Choco Mucho Cookies','30g',10),
('LBC066','Loaf, Biscuits & Crackers','Presto Cream Sandwich','30g',8),
('LBC067','Loaf, Biscuits & Crackers','Presto Peanut Butter Sandwich','30g',8),
('LBC068','Loaf, Biscuits & Crackers','Presto Chocolate Sandwich','30g',8),
('LBC069','Loaf, Biscuits & Crackers','Lemon Square Inipit','40g',10),
('LBC070','Loaf, Biscuits & Crackers','Lemon Square Custaroons','40g',10),
('LBC071','Loaf, Biscuits & Crackers','Bread Stix','30g',8),
('LBC072','Loaf, Biscuits & Crackers','Bread Pan','40g',10),
('LBC073','Loaf, Biscuits & Crackers','Rebisco Butter Coconut','30g',8),
('LBC074','Loaf, Biscuits & Crackers','Rebisco Graham Crackers','200g',40),
('LBC075','Loaf, Biscuits & Crackers','SkyFlakes Family Pack','250g',45),
('LBC076','Loaf, Biscuits & Crackers','Fita Family Pack','300g',50),
('LBC077','Loaf, Biscuits & Crackers','Hansel Family Pack','300g',50),
('LBC078','Loaf, Biscuits & Crackers','Cream-O Family Pack','300g',65),
('LBC079','Loaf, Biscuits & Crackers','Oreo Family Pack','300g',85),
('LBC080','Loaf, Biscuits & Crackers','Fibisco Graham Crackers','200g',40),
('PJD001','Powdered Juice & Other Drinks','Tang Orange','25g',8),
('PJD002','Powdered Juice & Other Drinks','Tang Four Seasons','25g',8),
('PJD003','Powdered Juice & Other Drinks','Tang Mango','25g',8),
('PJD004','Powdered Juice & Other Drinks','Tang Pineapple','25g',8),
('PJD005','Powdered Juice & Other Drinks','Tang Pomelo','25g',8),
('PJD006','Powdered Juice & Other Drinks','Tang Orange','250g',65),
('PJD007','Powdered Juice & Other Drinks','Tang Four Seasons','250g',65),
('PJD008','Powdered Juice & Other Drinks','Eight O\'Clock Orange','20g',7),
('PJD009','Powdered Juice & Other Drinks','Eight O\'Clock Four Seasons','20g',7),
('PJD010','Powdered Juice & Other Drinks','Eight O\'Clock Orange','100g',25),
('PJD011','Powdered Juice & Other Drinks','Eight O\'Clock Four Seasons','100g',25),
('PJD012','Powdered Juice & Other Drinks','Nestea Iced Tea Lemon','25g',10),
('PJD013','Powdered Juice & Other Drinks','Nestea Iced Tea Lemon','50g',20),
('PJD014','Powdered Juice & Other Drinks','Nestea Iced Tea Lemon','200g',65),
('PJD015','Powdered Juice & Other Drinks','Nestea Iced Tea Lemon','300g',95),
('PJD016','Powdered Juice & Other Drinks','Nestea Iced Tea Peach','25g',10),
('PJD017','Powdered Juice & Other Drinks','Nestea Iced Tea Apple','25g',10),
('PJD018','Powdered Juice & Other Drinks','Nestea Iced Tea Lemon','10x25g',90),
('PJD019','Powdered Juice & Other Drinks','Milo Chocolate Malt Drink','24g',9),
('PJD020','Powdered Juice & Other Drinks','Ovaltine All-In-One','20g',10),
('PJD021','Powdered Juice & Other Drinks','Energen Chocolate','30g',10),
('PJD022','Powdered Juice & Other Drinks','Energen Vanilla','30g',10),
('PJD023','Powdered Juice & Other Drinks','Energen Ginger','30g',10),
('PJD024','Powdered Juice & Other Drinks','Energen Chocolate','10x30g',100),
('PJD025','Powdered Juice & Other Drinks','Swiss Miss Chocolate Drink','25g',20),
('PJD026','Powdered Juice & Other Drinks','Kool-Aid Orange','~20g',8),
('PJD027','Powdered Juice & Other Drinks','Kool-Aid Tropical Punch','~20g',8),
('PJD028','Powdered Juice & Other Drinks','Kool-Aid Grape','~20g',8),
('PJD029','Powdered Juice & Other Drinks','Kool-Aid Strawberry','~20g',8),
('PJD030','Powdered Juice & Other Drinks','Zesto Powdered Juice Drink','~20g',5),
('PJD031','Powdered Juice & Other Drinks','Sunquick Powdered Juice Drink','~20g',8),
('PJD032','Powdered Juice & Other Drinks','Royal Instant Powdered Drink','~20g',8),
('PJD033','Powdered Juice & Other Drinks','Calamansi Juice Powder','~20g',5),
('PJD034','Powdered Juice & Other Drinks','Lemon Juice Powder','~20g',5),
('PJD035','Powdered Juice & Other Drinks','Orange Juice Powder','~20g',5),
('PJD036','Powdered Juice & Other Drinks','Mango Juice Powder','~20g',5),
('PJD037','Powdered Juice & Other Drinks','Four Seasons Juice Powder','~20g',5),
('PJD038','Powdered Juice & Other Drinks','Buko Pandan Drink Powder','~25g',8),
('PJD039','Powdered Juice & Other Drinks','Sago\'t Gulaman Drink Powder','~25g',8),
('PJD040','Powdered Juice & Other Drinks','Gulaman Powder','25g',8),
('PJD041','Powdered Juice & Other Drinks','Mr. Gulaman Unflavored','25g',8),
('PJD042','Powdered Juice & Other Drinks','Mr. Gulaman Red','25g',8),
('PJD043','Powdered Juice & Other Drinks','Mr. Gulaman Green','25g',8),
('PJD044','Powdered Juice & Other Drinks','Mr. Gulaman Orange','25g',8),
('PJD045','Powdered Juice & Other Drinks','Jell-O Gelatin Powder','85g',55),
('PJD046','Powdered Juice & Other Drinks','Alsa Gulaman Powder','90g',35),
('PJD047','Powdered Juice & Other Drinks','Alsa Jelly Powder','90g',35),
('PJD048','Powdered Juice & Other Drinks','Alsa Gulaman Orange','90g',35),
('PJD049','Powdered Juice & Other Drinks','Alsa Gulaman Red','90g',35),
('PJD050','Powdered Juice & Other Drinks','Alsa Gulaman Green','90g',35),
('PJD051','Powdered Juice & Other Drinks','Nescafé 3-in-1 Coffee','20-26g',8),
('PJD052','Powdered Juice & Other Drinks','Kopiko Brown 3-in-1','25g',8),
('PJD053','Powdered Juice & Other Drinks','Great Taste White','30g',8),
('PJD054','Powdered Juice & Other Drinks','Tang Orange','20g Twin Pack',15),
('PJD055','Powdered Juice & Other Drinks','Tang Four Seasons','20g Twin Pack',15),
('PJD056','Powdered Juice & Other Drinks','Nestea Lemon','25g Twin Pack',18),
('PJD057','Powdered Juice & Other Drinks','Eight O\'Clock Orange','20g Twin Pack',13),
('PJD058','Powdered Juice & Other Drinks','Milo Twin Pack','48g',17),
('PJD059','Powdered Juice & Other Drinks','Ovaltine All-In-One','20g x10',105),
('PJD060','Powdered Juice & Other Drinks','Energen Chocolate','30g x10',100);
